<?php

namespace Doku\Snap\Commons;

/**
 * Enum representing the available virtual account channels.
 */
class VaChannels
{
    const VIRTUAL_ACCOUNT_CHANNELSS = [
        'VIRTUAL_ACCOUNT_BCA',
        'VIRTUAL_ACCOUNT_BANK_MANDIRI',
        'VIRTUAL_ACCOUNT_BRI',
        'VIRTUAL_ACCOUNT_BNI',
        'VIRTUAL_ACCOUNT_BANK_DANAMON',
        'VIRTUAL_ACCOUNT_BANK_PERMATA',
        'VIRTUAL_ACCOUNT_MAYBANK',
        'VIRTUAL_ACCOUNT_BNC',
        'VIRTUAL_ACCOUNT_BTN',
        'VIRTUAL_ACCOUNT_BSI',
        'VIRTUAL_ACCOUNT_BANK_CIMB',
        'VIRTUAL_ACCOUNT_SINARMAS',
        'VIRTUAL_ACCOUNT_DOKU',
        'VIRTUAL_ACCOUNT_BSS',
    ];

    const MAP_OCO_TO_CSNAP_CHANNEL = [
        '47' => 'VIRTUAL_ACCOUNT_DOKU',
        '22' => 'VIRTUAL_ACCOUNT_SINARMAS',
        '41' => 'VIRTUAL_ACCOUNT_BANK_MANDIRI',
        '44' => 'VIRTUAL_ACCOUNT_MAYBANK',
        '21' => 'VIRTUAL_ACCOUNT_SINARMAS_FULL',
        '42' => 'VIRTUAL_ACCOUNT_QNB',
        '43' => 'VIRTUAL_ACCOUNT_BTN',
        '34' => 'VIRTUAL_ACCOUNT_BRI',
        '08' => 'VIRTUAL_ACCOUNT_BANK_MANDIRI',
        '29' => 'VIRTUAL_ACCOUNT_BCA',
        '40' => 'VIRTUAL_ACCOUNT_BNI',
        '38' => 'VIRTUAL_ACCOUNT_BNI',
        '33' => 'VIRTUAL_ACCOUNT_BANK_DANAMON',
        '07' => 'VIRTUAL_ACCOUNT_BANK_PERMATA',
        '32' => 'VIRTUAL_ACCOUNT_BANK_CIMB',
        '05' => 'VIRTUAL_ACCOUNT_BANK_PERMATA',
        '36' => 'VIRTUAL_ACCOUNT_BANK_PERMATA',
        '09' => 'VIRTUAL_ACCOUNT_BANK_MANDIRI',
    ];

    const MAP_SNAP_TO_OCO_CHANNEL = [
        'VIRTUAL_ACCOUNT_DOKU' => '47',
        'VIRTUAL_ACCOUNT_SINARMAS' => '22',
        'VIRTUAL_ACCOUNT_BANK_MANDIRI' => '08',
        'VIRTUAL_ACCOUNT_MAYBANK' => '44',
        'VIRTUAL_ACCOUNT_SINARMAS_FULL' => '21',
        'VIRTUAL_ACCOUNT_QNB' => '42',
        'VIRTUAL_ACCOUNT_BTN' => '43',
        'VIRTUAL_ACCOUNT_BRI' => '34',
        'VIRTUAL_ACCOUNT_BCA' => '29',
        'VIRTUAL_ACCOUNT_BNI' => '38',
        'VIRTUAL_ACCOUNT_BANK_DANAMON' => '33',
        'VIRTUAL_ACCOUNT_BANK_PERMATA' => '05',
        'VIRTUAL_ACCOUNT_BANK_CIMB' => '32',
    ];
}
